# gradio
SESSION_WINDOW_SIZE = 2

# websearch service
SEARCH_SERVER_URL = "http://localhost:8021/search"
NUM_SEARCH_WEBPAGES = 5
WEBPAGE_LOAD_TIMETOUT = 10.0
PROXIES = {
    "http": None,
    "https": None,
}


# model
MODEL_NAME = "megrez"
MODEL_SERVER_URL = "http://localhost:8011/v1/"
STOP_TOKENS = ["<|turn_end|>"]
FUNCTION_START_TOKEN, FUNCTION_END_TOKEN = "<|function_start|>", "<|function_end|>"
MAX_ACTION_TURNS = 1

WEBPAGE_SUMMARY_MAX_INPUT_TOKENS = 2048
WEBPAGE_SUMMARY_MAX_OUTPUT_TOKENS = 512
SESSION_MAX_INPUT_TOKENS = 3072
CHAT_TEMPERATURE = 0.4
CHAT_MAX_OUTPUT_TOKENS = 2048
AGENT_TEMPERATURE = 0.01
AGENT_MAX_OUTPUT_TOKENS = 512
